//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8937
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazzasBazaar.Service
{
    using System.Runtime.Serialization;



    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AvailableProductCountField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableProductCount
        {
            get
            {
                return this.AvailableProductCountField;
            }
            set
            {
                this.AvailableProductCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CategoryIdField;
        
        private string CategoryNameField;
        
        private string DescriptionField;
        
        private string EanField;
        
        private System.Nullable<System.DateTime> ExpectedRestockField;
        
        private int IdField;
        
        private bool InStockField;
        
        private string NameField;
        
        private double PriceForOneField;
        
        private double PriceForTenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId
        {
            get
            {
                return this.CategoryIdField;
            }
            set
            {
                this.CategoryIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ean
        {
            get
            {
                return this.EanField;
            }
            set
            {
                this.EanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpectedRestock
        {
            get
            {
                return this.ExpectedRestockField;
            }
            set
            {
                this.ExpectedRestockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InStock
        {
            get
            {
                return this.InStockField;
            }
            set
            {
                this.InStockField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForOne
        {
            get
            {
                return this.PriceForOneField;
            }
            set
            {
                this.PriceForOneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceForTen
        {
            get
            {
                return this.PriceForTenField;
            }
            set
            {
                this.PriceForTenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/BazzasBazaar.Service")]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AccountNameField;
        
        private string CardNumberField;
        
        private int IdField;
        
        private string ProductEanField;
        
        private int ProductIdField;
        
        private string ProductNameField;
        
        private int QuantityField;
        
        private double TotalPriceField;
        
        private System.DateTime WhenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName
        {
            get
            {
                return this.AccountNameField;
            }
            set
            {
                this.AccountNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber
        {
            get
            {
                return this.CardNumberField;
            }
            set
            {
                this.CardNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductEan
        {
            get
            {
                return this.ProductEanField;
            }
            set
            {
                this.ProductEanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId
        {
            get
            {
                return this.ProductIdField;
            }
            set
            {
                this.ProductIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity
        {
            get
            {
                return this.QuantityField;
            }
            set
            {
                this.QuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalPrice
        {
            get
            {
                return this.TotalPriceField;
            }
            set
            {
                this.TotalPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime When
        {
            get
            {
                return this.WhenField;
            }
            set
            {
                this.WhenField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IStore")]
public interface IStore
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetAllCategories", ReplyAction="http://tempuri.org/IStore/GetAllCategoriesResponse")]
    BazzasBazaar.Service.Category[] GetAllCategories();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetCategoryById", ReplyAction="http://tempuri.org/IStore/GetCategoryByIdResponse")]
    BazzasBazaar.Service.Category GetCategoryById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetFilteredProducts", ReplyAction="http://tempuri.org/IStore/GetFilteredProductsResponse")]
    BazzasBazaar.Service.Product[] GetFilteredProducts(System.Nullable<int> categoryId, string categoryName, System.Nullable<double> minPrice, System.Nullable<double> maxPrice);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetProductById", ReplyAction="http://tempuri.org/IStore/GetProductByIdResponse")]
    BazzasBazaar.Service.Product GetProductById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/GetOrderById", ReplyAction="http://tempuri.org/IStore/GetOrderByIdResponse")]
    BazzasBazaar.Service.Order GetOrderById(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CreateOrder", ReplyAction="http://tempuri.org/IStore/CreateOrderResponse")]
    BazzasBazaar.Service.Order CreateOrder(string accountName, string cardNumber, int productId, int quantity);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStore/CancelOrderById", ReplyAction="http://tempuri.org/IStore/CancelOrderByIdResponse")]
    bool CancelOrderById(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IStoreChannel : IStore, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class StoreClient : System.ServiceModel.ClientBase<IStore>, IStore
{
    
    public StoreClient()
    {
    }
    
    public StoreClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public StoreClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public StoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public BazzasBazaar.Service.Category[] GetAllCategories()
    {
        return base.Channel.GetAllCategories();
    }
    
    public BazzasBazaar.Service.Category GetCategoryById(int id)
    {
        return base.Channel.GetCategoryById(id);
    }
    
    public BazzasBazaar.Service.Product[] GetFilteredProducts(System.Nullable<int> categoryId, string categoryName, System.Nullable<double> minPrice, System.Nullable<double> maxPrice)
    {
        return base.Channel.GetFilteredProducts(categoryId, categoryName, minPrice, maxPrice);
    }
    
    public BazzasBazaar.Service.Product GetProductById(int id)
    {
        return base.Channel.GetProductById(id);
    }
    
    public BazzasBazaar.Service.Order GetOrderById(int id)
    {
        return base.Channel.GetOrderById(id);
    }
    
    public BazzasBazaar.Service.Order CreateOrder(string accountName, string cardNumber, int productId, int quantity)
    {
        return base.Channel.CreateOrder(accountName, cardNumber, productId, quantity);
    }
    
    public bool CancelOrderById(int id)
    {
        return base.Channel.CancelOrderById(id);
    }
}
